// frontend-ng/src/app/components/traffic-light/traffic-light.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

const STATUS_MAP: Record<string, { color: string; label: string; bg: string }> = {
  PENDING:     { color: '#dc2626', label: 'Pendiente',   bg: '#fef2f2' },
  IN_PROGRESS: { color: '#d97706', label: 'En Proceso',  bg: '#fffbeb' },
  DONE:        { color: '#16a34a', label: 'Completado',  bg: '#f0fdf4' },
  BLOCKED:     { color: '#dc2626', label: 'Bloqueado',   bg: '#fef2f2' },
  OPEN:        { color: '#2563eb', label: 'Abierto',     bg: '#eff6ff' },
  COMPLETED:   { color: '#16a34a', label: 'Completado',  bg: '#f0fdf4' },
  CANCELLED:   { color: '#6b7280', label: 'Cancelado',   bg: '#f9fafb' },
  ACTIVE:      { color: '#16a34a', label: 'Activo',      bg: '#f0fdf4' },
  DRAFT:       { color: '#d97706', label: 'Borrador',    bg: '#fffbeb' },
};

@Component({
  selector: 'app-traffic-light',
  standalone: true,
  imports: [CommonModule],
  template: `
    <span class="traffic-light"
          [style.background]="showLabel ? info.bg : 'transparent'"
          [style.border]="showLabel ? ('1px solid ' + info.color + '44') : 'none'"
          [style.border-radius.px]="showLabel ? 20 : 0"
          [style.padding]="showLabel ? '3px 10px 3px 7px' : '0'"
          [style.display]="'inline-flex'" [style.align-items]="'center'" [style.gap.px]="5">
      <span class="traffic-dot"
            [style.width.px]="showLabel ? 10 : size"
            [style.height.px]="showLabel ? 10 : size"
            [style.border-radius]="'50%'"
            [style.background]="info.color"
            [style.flex-shrink]="'0'"></span>
      @if (showLabel) {
        <span [style.color]="info.color" [style.font-size.px]="12" [style.font-weight]="600">{{ info.label }}</span>
      }
    </span>
  `
})
export class TrafficLightComponent {
  @Input() status = '';
  @Input() size = 10;
  @Input() showLabel = false;

  get info() { return STATUS_MAP[this.status] ?? { color: '#9ca3af', label: this.status, bg: '#f9fafb' }; }
}

// frontend/src/components/TrafficLight.tsx
interface Props {
  status: string;
  size?: number;
  showLabel?: boolean;
}

const STATUS_CONFIG: Record<string, { color: string; glow: string; label: string }> = {
  DONE: { color: '#10b981', glow: 'rgba(16,185,129,.4)', label: 'Completado' },
  COMPLETED: { color: '#10b981', glow: 'rgba(16,185,129,.4)', label: 'Completado' },
  IN_PROGRESS: { color: '#f59e0b', glow: 'rgba(245,158,11,.4)', label: 'En progreso' },
  PENDING: { color: '#ef4444', glow: 'rgba(239,68,68,.4)', label: 'Pendiente' },
  OPEN: { color: '#f59e0b', glow: 'rgba(245,158,11,.4)', label: 'Abierto' },
  BLOCKED: { color: '#ef4444', glow: 'rgba(239,68,68,.4)', label: 'Bloqueado' },
  CANCELLED: { color: '#64748b', glow: 'rgba(100,116,139,.4)', label: 'Cancelado' },
};

export default function TrafficLight({ status, size = 14, showLabel = false }: Props) {
  const config = STATUS_CONFIG[status] || STATUS_CONFIG.PENDING;

  return (
    <span className="traffic-light" title={config.label}>
      <span
        className="traffic-dot"
        style={{
          width: size,
          height: size,
          background: config.color,
          boxShadow: `0 0 ${size * 0.6}px ${config.glow}`,
        }}
      />
      {showLabel && <span className="traffic-label">{config.label}</span>}
    </span>
  );
}
